import pandas as pd
import numpy as np
from .helper_normalise import normalise_by_method

#function that generates the State of Charge proxy given a pandas dataframe containing timeseries information, meta data, and some system config data
def generate_SoC_proxy(
    df_timeseries: pd.DataFrame, 
    demand_field: str='demand_power', 
    renewables_fields_and_weights: dict = {
        'solar':1,
        'onshore_wind': 1,
        'offshore_wind': 1
        }
    ):

    #Quick process for checking all the fields exist and also gathering the names of the renewables
    missing_fields = []
    renewable_fields = []
    if  demand_field not in df_timeseries.columns:
        missing_fields.append(demand_field)
    for key in renewables_fields_and_weights:
        renewable_fields.append(key) 
        if key not in df_timeseries:
            missing_fields.append(key)
    if missing_fields:
        raise Exception(f"The following fields are missing from the dataframe: {missing_fields}")

    #normalise demand by mean
    normalise_by_method(df_timeseries[demand_field], method='mean', inplace=True)

    #normalise capacity factors by sum, for unity across summation
    normalise_by_method(renewables_fields_and_weights, method='sum', inplace=True)

    #For each timestep, divide the renewables capacity factors by the normalised demand for that timestep, to get capacity factors relative to demand
    #This seeks to capture events where renewable output is low, but so is demand, i.e. no issues with supply.
    df_timeseries[renewable_fields] = df_timeseries[renewable_fields].div(df_timeseries[demand_field], axis=0)

    #compute the threshold between charge states and discharge states that govern the State of Charge proxy
    threshold_SoC = 0
    for i in renewable_fields:
        threshold_SoC += df_timeseries[i].mean()*renewables_fields_and_weights[i]
    
    #compute surplus estimates using renewable profiles and relative weights
    df_timeseries['surplus'] = (
        sum(df_timeseries[field] * renewables_fields_and_weights[field] for field in renewable_fields)
        - threshold_SoC
    )

    #compute the cumulation of surplus i.e. the state of charge proxy
    df_timeseries['soc_proxy'] = df_timeseries['surplus'].cumsum()

    #apply a correction for floating point noise i.e. we want a value of 0 at the end not #1e-9
    numeric_columns = df_timeseries.select_dtypes(include=[np.number]).columns #gather all the numeric columns including the ones generated by this function to apply correction
    arr = df_timeseries[numeric_columns].to_numpy()
    arr[np.isclose(arr, 0, atol=1e-9)] = 0 #threshold set to 1e-9. Could be tighter but this seems adequate for a proxy.
    df_timeseries[numeric_columns] = arr 

    #return the timeseries with new SoC Proxy as well as the threshold
    return df_timeseries, threshold_SoC

