#Useful utility functions 

#File-naming function for standard models generated by constructor
def filename_standard(params, type):
    filename=f"{params['scenario_name']}_{params['horizon_start'][:4]}_{params['horizon_end'][:4]}_{params['output_model_name']}.{type}"
    return filename